import { Movie } from "./models/Movies";

export const movies: Movie[] = [
  {
    id: 1,
    name: "Avengers: Endgame(INOX)",
    language: "English",
    ticketCost: 200,
    rows: 20,
    cols: 6,
    seats: {
      A: Array(20).fill(0),
      B: Array(20).fill(0),
      C: Array(20).fill(0),
      D: Array(20).fill(0),
      E: Array(20).fill(0),
      F: Array(20).fill(0),
      G: Array(20).fill(0),
    },
  },
  {
    id: 2,
    name: "Uri: The Surgical Strike(PVR)",
    language: "Hindi",
    ticketCost: 200,
    rows: 20,
    cols: 6,
    seats: {
      A: Array(20).fill(0),
      B: Array(20).fill(0),
      C: Array(20).fill(0),
      D: Array(20).fill(0),
      E: Array(20).fill(0),
      F: Array(20).fill(0),
      G: Array(20).fill(0),
    },
  },
  {
    id: 3,
    name: "KGF: Chapter 1(Cinepolis)",
    language: "Kannada",
    ticketCost: 200,
    rows: 20,
    cols: 6,
    seats: {
      A: Array(20).fill(0),
      B: Array(20).fill(0),
      C: Array(20).fill(0),
      D: Array(20).fill(0),
      E: Array(20).fill(0),
      F: Array(20).fill(0),
      G: Array(20).fill(0),
    },
  },
  {
    id: 4,
    name: "Master(PVR)",
    language: "Tamil",
    ticketCost: 200,
    rows: 20,
    cols: 6,
    seats: {
      A: Array(20).fill(0),
      B: Array(20).fill(0),
      C: Array(20).fill(0),
      D: Array(20).fill(0),
      E: Array(20).fill(0),
      F: Array(20).fill(0),
      G: Array(20).fill(0),
    },
  },
  {
    id: 5,
    name: "Bahubali: The beginning(INOX)",
    language: "Telugu",
    ticketCost: 200,
    rows: 20,
    cols: 6,
    seats: {
      A: Array(20).fill(0),
      B: Array(20).fill(0),
      C: Array(20).fill(0),
      D: Array(20).fill(0),
      E: Array(20).fill(0),
      F: Array(20).fill(0),
      G: Array(20).fill(0),
    },
  },
];
